# https://yarnpkg.com/configuration/yarnrc#nodeLinker
# nodeLinker: "pnpm" # If you can't support Plug-n-Play style
enableInlineBuilds: true # Display postInstall logs

npmMinimalAgeGate: "1w"
npmPreapprovedPackages:
  # We own these packages
  - "eslint-config-beslogic" 
  - "@beslogic/utils"
  - "@beslogic/rxjs-utils"
  - "@beslogic/angular-utils"
  - "@beslogic/react-utils"
